export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_DONE = 'FETCH_DONE';
export const FETCH_FAILED = 'FETCH_FAILED';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';